armbian/configng

functions/bash-utility-master/src/os.sh

We use this extensively, so better to add to the main library

Add support for Linux code name to Bash Utility

---

bin/armbian-interface

Fixed some armbian-interface shellcheck errors and warnings

fix for shellcheck error

---

debian.conf

removed unused folder in debian.conf
removed usr/share/ on line one

Fix workflow

---

.github/workflows/debian.yml
lib/armbian-configng/config.ng.functions.sh

When coming from minimal image, those are not installed but are needed.
It shows no error but doesn't work and it works after this is installed.

Add jq whiptail and to default package dependencies

---

lib/armbian-configng/config.ng.docs.sh
lib/armbian-configng/config.ng.functions.sh

no longer receive null error 
sub sub item iterating
tested with --help
sub sub items executing 
tested on https://github.com/armbian/configng/pull/55
added jq check for sub  sub items

Bug fix, jq Null error  

---

lib/armbian-configng/config.ng.functions.sh
lib/armbian-configng/config.ng.runtime.sh

- we will store overlay dir at build time https://github.com/armbian/…build/pull/7198
- keep window clean of not needed informations
- fix wront title / backtitle settings
Several manual runs

Remove OVERLAY decision as it will be done at build time

---

.github/ISSUE_TEMPLATE/1-bugreport.yml
.github/ISSUE_TEMPLATE/2-feature.yml
.github/ISSUE_TEMPLATE/3-task.yml
.github/ISSUE_TEMPLATE/config.yml

Add iisue templates similar to those from main build framework

---

lib/armbian-configng/config.ng.jobs.json
lib/armbian-configng/config.ng.system.sh

- reworking desktop install
- moving applications around

Refactor applications, add desktop execution

---

lib/armbian-configng/config.ng.network.sh

UX: when fixing IP address propose existing

---

lib/armbian-configng/config.ng.jobs.json
lib/armbian-configng/config.ng.system.sh

Some improvements

---

lib/armbian-configng/config.ng.docs.sh
lib/armbian-configng/config.ng.jobs.json
lib/armbian-configng/config.ng.network.sh

- adding network status display to the menu
- resolving bug for not selecting adaptor without IP address
- add support for adding default route and DNS 
Manual testing, enabling, disabling ...

Add support for editing default route and DNS

---

.editorconfig

Add editor config to define common coding style

---

lib/armbian-configng/config.ng.jobs.json
lib/armbian-configng/config.ng.system.sh

Uses already prepared functionality.
Several manual tests.

Add mechanism for motd management

---

lib/armbian-configng/config.ng.jobs.json

Bugfix. Returning code that was accidentally removed.

Bugfix: Install alternative kernels falled from the menu JSON

---

bin/armbian-configng
lib/armbian-configng/config.ng.docs.sh
lib/armbian-configng/config.ng.functions.sh
lib/armbian-configng/config.ng.network.sh
lib/armbian-configng/config.ng.runtime.sh
lib/armbian-configng/config.ng.system.sh

No functional changes - just style formatting.
Using this tool:
https://github.com/mvdan/sh

Run shell format on all bash files to match coding style

---

.github/workflows/lint.yml

Bump Checkout action on lint action

---

.github/dependabot.yml

Enable actions modules auto updating.

Github: Enable dependabot to make PR's for automatic updates

---

.github/workflows/docs.yml
lib/armbian-configng/config.ng.docs.sh

Generate documentation to DOCUMENTATION.md and opens a PR if there are changes. No other changes to the documentation content / structual wise.
Action was tested at PR and opens a PR.

Add action for rebuilding documentation

---

lib/armbian-configng/config.ng.docs.sh

We don't need time generation property here. This is already in the commit.

Remove `updated` section as will keep opening new pull requests

---

lib/armbian-configng/config.ng.functions.sh
lib/armbian-configng/config.ng.system.sh

Closing bug. Apt update is needed when we switch beta / stable repo.
Issue reference:  https://github.com/armbian/configng/issues/125

Bugfix: firmware switch function was not working correctly

---

README.md

Typo.
Copy / paste works as expected.

Fix wrong quotation marks

---

.github/workflows/unit-tests.yml

We don't need to test on Debian testing.

Remove Trixe from unit tests as it often fails

---

lib/armbian-configng/config.ng.functions.sh
lib/armbian-configng/config.ng.jobs.json

As tittle says. Small design change.

Code consistency: we have statuses with Caps, so lets change disabled to Disabled

---

lib/armbian-configng/config.ng.jobs.json
lib/armbian-configng/config.ng.system.sh

Adding overlay management per family and per SoC.
Small improvements to prior implementation - added limitation to SoC.

Add device tree overlay management

---

lib/armbian-configng/config.ng.jobs.json

Closing: https://github.com/armbian/configng/issues/146

SSH daemon have different service names at Ubuntu and Debian

---

lib/armbian-configng/config.ng.system.sh

As the title says.
- Manual testing.

UX / cosmetic: when changing MOTD, show it after exit from function

---

lib/armbian-configng/config.ng.functions.sh

This method was not working:
- if kernel was uninstalled 
- on Ubuntu Oracular

Improve kernel switching methodology

---

lib/armbian-configng/config.ng.jobs.json
lib/armbian-configng/config.ng.system.sh
tools/json/config.localisation.json

Trivial change - adding a function instead of calling it directly from JSON.

Move change hostname function from JSON file

---

lib/armbian-configng/config.ng.docs.sh

Add TUX to the head of the document

---

lib/armbian-configng/config.ng.runtime.sh

Cockpit 
Plex and emby
Theoretically, it should now be able to change the ports, and they will dynamically reflect the ports being used.

161-feature-request-store-and-show-port-number

---

.github/workflows/docs.yml
.github/workflows/ftp-deploy.yml.hold
.github/workflows/unit-tests.yml
README.md
bin/armbian-config
lib/armbian-configng/config.ng.docs.sh
share/applications/configng.desktop
tests/S17.conf

Change to armbian-config also in Unit test CI

---

.github/workflows/unit-tests.yml

Fixing unit tests execution

---

lib/armbian-configng/config.ng.network.sh

Add an option to change / spoof MAC address of adaptor.
Standard NetPlan way. Some adaptors won't accept this.

Add support for changing / spoofing MAC address

---

.github/workflows/docs.yml

Joins JSON parts into runtime JSON file at push. In case we forgot to run this command while development.
Actions scripts.
Tested at PR.

Add JSON generation to the docs generation

---

.github/workflows/unit-tests.yml

Unit test bug-fix - broken if checking one test at PR

---

.github/workflows/unit-tests.yml

Mitigating Debian / Ubuntu diffs.

Install netcat-traditional instead of netcat

---

.github/workflows/docs.yml
tools/config-jobs
tools/json/config.help.json
tools/json/config.localisation.json
tools/json/config.network.json
tools/json/config.software.json
tools/json/config.system.json

This option allows outputting a chosen filename or using the default filename for testing disabled titles.
This option allows outputting a chosen filename or using the default filename for excluding disabled title
use default file name 
```
./tools/config-jobs -t || -p
```
use custom name
```
./tools/config-jobs -t /path/to/file/name.json || -p /path/to/file/name.json
```

add: -t "test" and -p "production" option to json assembiling

---

.github/workflows/unit-tests.yml

- add missing package
- hardening test execution

Fix small troubles with unit tests

---

.github/workflows/docs.yml

Fixes due to structural changes.

Documentation CI: assemble parts before making it

---

.github/workflows/docs.yml

Update docs.yml to correct json name

---

.github/ISSUE_TEMPLATE/bug-reports.yml

Issue reference:  https://github.com/armbian/configng/issues/222

Cosmetic: fixing link in the bug issue template

---

.github/workflows/issue-welcome-first-time.yml
.github/workflows/watchdog.yml

In title. Copy from our other repos.

Git hub actions: add watchdog to repeat unit tests once and issue auto welcome

---

tools/modules/system/switch_kernels.sh

Issue reference:  https://github.com/armbian/configng/issues/226

Bugfix: add missing character from character manipulation

---

tests/MON001.conf
tools/include/markdown/MON001-footer.md
tools/json/config.software.json
tools/modules/software/install_uptime-kuma.sh

Uptime Kuma is an easy-to-use self-hosted monitoring tool.
https://user-images.githubusercontent.com/1336778/212262296-e6205815-ad62-488c-83ec-a5b0d0689f7c.jpg
Related documentation: https://github.com/louislam/uptime-kuma
Docker.

Software title: add Uptime Kuma, self-hosted monitoring tool

---

tools/json/config.software.json

Doubled key numbers in the JSON menu. This broke installation of github utility

Fixing wront number in JSON structure

---

README.md

Adding a link to documentation for adding a new feature. Perhaps having that as first link?

Add link to adding new feature

---

debian.conf
etc/apt/sources.list.d/armbian-config.list

In order to keep package updating when installed from this repository updated, add a package repository generated by this repo.
Tested on fork.

Add repository list to the Debian package

---

tools/include/markdown/NE002-footer.md

Add instructions how to check if network device is supported.

Documentation: add additional info to network settings

---

tools/include/markdown/NE002-header.md

Adding schematic for network settings

---

tools/modules/network/network_config.sh

Issue reference:  https://github.com/armbian/configng/issues/283

Wireless networking: retry 3 times for getting stations

---

tools/modules/software/install_jellyseerr.sh

Bugfix: set correct folder name

---

tools/modules/network/network_config.sh

- improve selecting stability
- adding information about strength and frequency
- supporting spaces in SSID name
https://github.com/armbian/configng/issues/283
BASH

Wireless discovery hardening

---

tools/modules/functions/check_distro_status.sh

Cosmetic: fix line breaking in warning message

---

tests/SY009.conf

Removing deprecated unit tests.

Remove wrong unit test definitions

---

tools/modules/software/install_docker.sh

Issue reference:  Closing https://github.com/armbian/configng/issues/327

Make sure docker group is added and user added to the group

---

tools/modules/system/module_armbian_runners.sh

Armbian runners deploy: fixing bugs

---

tools/modules/system/module_armbian_kvmtest.sh

- parameters workaround
- replacing hard coding with variable

Enabling KVM - small bugfix

---

tests/SY008.conf
tests/SY101.conf
tests/SY102.conf
tests/SY202.conf
tests/SY203.conf
tests/SY206.conf
tests/SY207.conf

Most are deprecated due to changed names and we anyway need different / better test logic.

Unit tests: drop several old test cases

---

tests/NAV001.conf
tools/json/config.software.json
tools/modules/software/module_navidrome.sh

Navidrome Music Server and Streamer compatible with Subsonic/Airsonic
Docker run.

Software title: Navidrome Music Server and Streamer

---

README.md

Debian package includes armbian-config.list. Lets synchronize with manual instructions.

Repository consistency: rename armbian-development to armbian-config.list

---

.github/ISSUE_TEMPLATE/bug-reports.yml

Closing https://github.com/armbian/configng/issues/338

Update issue template

---

tools/modules/system/module_armbian_kvmtest.sh

Oracular Ubuntu is no more, switching to Plucky

---

tools/json/config.system.json
tools/modules/system/module_nfs.sh
tools/modules/system/module_nfsd.sh

Small improvements for NFS / NFSd modules.
- add feature to show mounts
- add timeout for `showmount` as it tends to hangs if permissions on server are not set right
- create mount folder in case it doesn't already exists

NFS: several fixes to improve handling

---

tools/include/markdown/DNS001-footer.md
tools/include/markdown/DNS001-header.md
tools/modules/software/module_adguardhome.sh
tools/modules/software/module_pi-hole.sh

Pi-hole and adguardhome: addressing small bugs, hardening

---

tools/modules/functions/check_desktop.sh

Small typo I've noticed while working on something else

Fix package name

---

tools/modules/system/module_armbian_kvmtest.sh
tools/modules/system/module_armbian_runners.sh

Fixing parameters handling in internal function.

KVM and runners deploy: fixing parameter readings

---

tools/modules/system/module_armbian_firmware.sh

Vendor branches needs an exception so we can switch between kernels.
Nanopi M6 (RK3588)

Kernel switching: manage exceptions (Rockchip vendor)

---

tools/json/config.software.json
tools/modules/software/module_armbianrouter.sh

This PR adds armbian-router to software section using docker containers.

Add armbian-router to software section

---

tools/modules/system/manage_zsh.sh

If this is not done, we can end up in no shell at all.

Module ZSH: update package before installing ZSH package

---

tools/modules/software/module_armbianrouter.sh

Add cdn.armbian.com to armbianrouter
Docker container.
- Already in production.

 software: armbianrouter: add cdn.armbian.com container 

---

tools/modules/software/module_haos.sh

Raspberry Pi doesn't support our way of setting kernel parameters. We need to add another exception to fix the problem.
Issue reference:  https://forum.armbian.com/topic/33245-armbian-with-preinstalled-home-assistant-supervised/page/3/#findComment-213857

HA on RaspberryPi: enable apparmor properly

---

tools/json/config.software.json
tools/modules/software/module_hastebin.sh

Armbian internal tool for running pastebin service.
Docker container.

Software title: add ANSI hastebin docker instance

---

tools/template/module_software_template.sh

Add arch to the module template

---

tools/json/config.software.json
tools/modules/software/module_zerotier.sh

A new Zerotier VPN software option has been added. It will allow us to create and manage SDN (Software Defined Networks) to intercommunicate different computers in a virtual private network (VPN) easily and quickly.
Related documentation: https://www.zerotier.com/

Add Zerotier into configng

---

.github/workflows/lint.yml
.github/workflows/unit-tests.yml

This reverts commit fbbdc83a9487035602ddf5088b2a2eada47b00a1 as it was fixed.

Revert "Change to different method of getting changed files"

---

tools/modules/software/module_prometheus.sh

Add editorconfig exclusion for block that needs a combination of spaces and tabs (yaml structure).
https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#excluding-blocks
@efectn

Add code style checking exception for Prometheus

---

tools/modules/software/module_hastebin.sh

This PR updates hastebin software to ensure compatibility with latest golang migration

software: switch hastebin to golang version

---

tools/modules/runtime/config.runtime.sh

Costmetic fix: do not gre rsync file if it doesn't exisits

---

bin/armbian-config

fixed calling check_distro_status

[bug] Fixed Non supported OS warning message. 

---

tools/modules/system/module_armbian_kvmtest.sh

Adjusting internally used functionality for deploying QCOW images for automated testing hosts.

KVM images deployment: switch to non-compressed cloud images

---

tools/modules/software/module_adguardhome.sh
tools/modules/software/module_armbianrouter.sh
tools/modules/software/module_bazarr.sh
tools/modules/software/module_deluge.sh
tools/modules/software/module_docker.sh
tools/modules/software/module_domoticz.sh
tools/modules/software/module_embyserver.sh
tools/modules/software/module_evcc.sh
tools/modules/software/module_grafana.sh
tools/modules/software/module_haos.sh
tools/modules/software/module_hastebin.sh

Refactor conditions to use if then fi otherwise tests cases are failing

---

tools/modules/software/module_adguardhome.sh
tools/modules/software/module_jellyseerr.sh
tools/modules/software/module_lidarr.sh
tools/modules/software/module_mariadb.sh
tools/modules/software/module_medusa.sh
tools/modules/software/module_netdata.sh
tools/modules/software/module_nextcloud.sh
tools/modules/software/module_octoprint.sh
tools/modules/software/module_owncloud.sh
tools/modules/software/module_phpmyadmin.sh
tools/modules/software/module_portainer.sh
tools/modules/software/module_uptime-kuma.sh

@coderabbitai can you apply same change for other scripts under tools/modules/software

Adjust condition to use proper if then fi style

---

tools/modules/software/module_adguardhome.sh

This PR changes the Docker network configuration for AdGuard Home from `--net=lsio` to `--network=host`. This change allows AdGuard Home to directly access the host network interfaces. Most importantly, this change fixes the DNS query logging problem by showing the real IP addresses of clients instead of internal Docker network IPs.
Issue reference: https://github.com/AdguardTeam/AdGuardHome/issues/4405
Related documentation: [[Docker networking documentation](https://docs.docker.com/network/host/)](https://docs.docker.com/network/host/)
*Provide a detailed description of the implementation. Include the following:*
- Changed Docker network configuration from `--net=lsio` to `--network=host`
- **Resolves issue with DNS query logging by showing real client IP addresses instead of internal …

Switch adguard home to network host for accurate client ip address logging

---

tools/modules/system/manage_dtoverlays.sh

- make separate overlay folder detection for Raspberry Pi
- show all overlays as we don't have consistency in naming them and many would be left out

Fixing bug on non Rpi boards for displaying overlays

---

tools/modules/runtime/config.runtime.sh

Due to recent refactoring of keyword, I forgot about adjusting run-time menu.

Adjust keywords for displaying links with ports in the menu

---

tests/postgres.conf
tools/include/markdown/PGSQL1-footer.md
tools/include/markdown/PGSQL1-header.md
tools/json/config.software.json
tools/modules/software/module_postgres.sh

This pull request introduces a fully automated Docker-based deployment of PostgreSQL inside Armbian Config.
The module simplifies the setup of PostgreSQL for developers, system administrators, and users who require a relational database.
Features
- ✅ Automated Docker Deployment using the `postgres:16-alpine` image.
- ✅ Accepts Parameters for database username, password, and database name (optional — defaults to armbian).
- ✅ Creates Data Volume for PostgreSQL persistence under /armbian/postgres/data.
- ✅ Correct Port Mapping (-p 5432:5432) for standard PostgreSQL client access.
- ✅ Automatic Fallback to Defaults if parameters are not specified.
- ✅ Support for Remove, Purge, Status operations via Armbian Config.
- ✅ Secure by default — password required or defaulted.
Changes
- Added new …

Software tittle: Add PostgreSQL Module Support

---

tools/modules/software/module_duplicati.sh

Bugfix: we need to use normal if, otherwise unit test return 1

---

.github/workflows/validate-json.yml
tools/json/config.help.json
tools/json/config.localisation.json
tools/json/config.network.json
tools/json/config.software.json
tools/json/config.system.json
tools/json/config.temp.json

This PR introduces a comprehensive and optimized GitHub Actions workflow to validate JSON configurations under config/tools/json/. Key improvements include:
🔧 Workflow Features:
Global EXCLUDED_IDS variable defined in env for consistency across all jobs.
Shared checkout job to reduce repetition and improve performance.
Separate jobs for:
- ✅ Checking for empty author fields
- 🔁 Detecting duplicate id values (excluding specified IDs)
- 🔢 Ensuring all ids are exactly 6 characters long (excluding specified IDs)
All issues are summarized clearly in the STEP_SUMMARY.
✅ Benefits:
Easier maintenance and cleaner output.
Scalable validation structure.
Future-proofed for additional rules (e.g., required fields, category validation).

Optimize JSON Validation Workflow

---

tools/json/config.software.json

Add ZeroTier short description to fit menu

---

tools/config-markdown.py
tools/json/config.localisation.json
tools/json/config.network.json
tools/json/config.software.json
tools/json/config.system.json
tools/modules/network/module_network_simple.sh
tools/modules/system/manage_odroid_board.sh
tools/modules/system/module_generic.sh

Documentation properties as such:

Update all missing connections between JSON and modules

---

tests/netbox.conf

Netbox: unit tests are failing - probably due to too small timeout

---

tools/include/markdown/IMM001-footer.md

Updated Immich data folders and docker container name for logs
Updated Immich data folders and docker container name for logs

Update IMM001-footer.md for immich

---

tools/config-markdown.py

Since files are sources from this repository but rendered to docs.armbian.com, we need to place direct links to files.
Header/Footer Edit Links Placement
Tested locally.

Add buttons for editing or adding header and footer

---

README.md

Improve clarity of main README.me

---

README.md

* Improve clarity of man README
* Update README.md
* Update README.md
* Update README.md
_Describe the tests you ran to verify your changes. Provide relevant details about your test …

Improve clarity of main README.me (#593)

---

tools/modules/software/module_haos.sh

Disable reboot in non-interactive

---

.github/workflows/issue-welcome-first-time.yml

Improve first time welcome text

---

tools/modules/system/module_armbian_runners.sh

Runner install: add missing dependencies

---

tools/json/config.software.json
tools/modules/runtime/config.runtime.sh
tools/modules/software/module_navidrome.sh

- and fixing permission issue with Navidrom
Related documentation: https://github.com/armbian/documentation/pull/756

Merge group `music` into `media` and sort the alphabetically 

---

tools/include/markdown/GHOST1-footer.md
tools/include/markdown/MYSQL1-footer.md

Typo fix - we need to have one space in order to render lists correctly

---

tools/include/markdown/PIH001-footer.md
tools/include/markdown/PIH001-header.md

Pi-Hole: updating documentation

---

tools/include/markdown/DOM001-header.md
tools/include/markdown/EMB001-footer.md
tools/include/markdown/GRA001-footer.md
tools/include/markdown/HAB001-footer.md
tools/include/markdown/HPG001-footer.md
tools/include/markdown/NCT001-footer.md
tools/include/markdown/PRO001-footer.md
tools/include/markdown/SABN01-footer.md
tools/include/markdown/STR001-footer.md
tools/json/config.software.json
tools/modules/runtime/config.runtime.sh
tools/modules/software/module_domoticz.sh
tools/modules/software/module_embyserver.sh
tools/modules/software/module_grafana.sh
tools/modules/software/module_homepage.sh
tools/modules/software/module_nextcloud.sh
tools/modules/software/module_prometheus.sh
tools/modules/software/module_sabnzbd.sh
tools/modules/software/module_stirling.sh
tools/modules/system/manage_dtoverlays.sh

Fix duplicate ports on most of the applications
