armbian/configng

lib/armbian-configng/config.ng.jobs.json
As title says.
Simple command execution. armbian-install is a part of BSP. Must be present ... do we need to check for presence?
=> Install to internal storage - calling armbian-install script

README.md, bin/armbian-configng, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh
=> Add support for changing login shells between ZSH and BASH

README.md, lib/armbian-configng/config.ng.docs.sh, lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json
Port SSHD server configuration from armbian-config. I hope this is all that needs to be done?
=> Enable support for adjusting SSH server

README.md, lib/armbian-configng/config.ng.jobs.json
Re-number JSON Added S to `sub sub system` , `SSxx` to help prevent duplicate ids
=> Re-numbered JSON SSXX for sub system to assist organizing 

README.md, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh
Switching between apt and beta repository.
To do: reload packages
=> Switch between stable and nighly repository

README.md, bin/armbian-configng, lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh
It extends functionality to reload packages too
Manual tests
=> Change set_safe_boot with improved function armbian_fw_manipulate

lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.network.sh
As we recently switched one level higher to defining network configuration via Netplan, all existing routines become deprecated. This commit adds initial support for handling wired and wireless networking. 
Problems - doesn't list sub routines:
`sudo bin/armbian-configng --cli N01`
jq: error (at bin/../lib/armbian-configng/config.ng.jobs.json:584): Cannot iterate over null (null)
Question:
What is simplest way to:
- pick and pass parameters further - IP, password
- collect users input via GUI  (reading IP, password, ...)
=> Refactoring network configuration

lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh
Enable / disable overlayrootfs aka virtual ready only mode. 
Works only in Ubuntu, Debian needs some tacking.
Tested manually under Ubuntu Noble on Odroid M1.
=> System: add virtual read-only overlayfs module

lib/armbian-configng/config.ng.docs.sh, lib/armbian-configng/config.ng.jobs.json
Removed --cmd from submenu as they do not work in cmd mode
Indented list to represent nested menus for readability
numbered sub menus with a "." for each nesting
Issue reference:  #67 
`armbian-configng --help`
```bash
Usage:  armbian-configng --[option]
Options:
--help [catagory]   Use [catagory] to filter specific menu options.
--cmd  [option]     Run a command from the menu (simple)
--api  [option]     Run a helper command        (advanced)
--doc               Generate the README.md file
Examples:
armbian-configng --help [cmd||System||Software||Network||Localisation]
armbian-configng --cmd help
armbian-configng --api help
```
`armbian-configng --help Network `
```bash 
Network - Fixed and wireless network settings (wlan0)
N01.1 - Configure network interfaces
N01.1.1 - Wired
--cmd N01 - …
```
=> 67 feature request tree structure when listing commands

lib/armbian-configng/config.ng.jobs.json
Prevent showing option where its n/a.
=> Netplan status only works with networkd type of networking

lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.network.sh
Refactor networking configuration logic to make it as easy as possible. 
- support for multiple interfaces which are being added to the bridge by default
- wireless adaptors in STA mode are not added to the bride as this method is not supported
- wireless adaptors in AP mode are added to wired bridge. hostapd is installed and enabled
- whole configuration can be set back to armbian defaults, which is DHCP on all wired interfaces
- while adding adaptor, it can be selected DHCP or fixed IP address
- old code for setting AP has been removed
It was tested with various scenarios, by using Network Manager and systemd-netword networking. Further tests are needed to make this functionality beyond breaking.
=> Refactor networking configuration logic

lib/armbian-configng/config.ng.system.sh
When running armbian-config headless and where terminal is not defined, we can't run debconf-apt-progress function. This adds a wrapper to check if terminal is defined and proceed accordingly.
Simple wrapper function.
Install packages on both methods:
```
debconf-apt-progress -- apt-get -y purge armbian-zsh
apt_install_wrapper apt-get -y purge armbian-zsh
```
=> Introduce apt_install_wrapper function to run apt commands depending on the terminal

lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh
Functionality for switching kernels. If scope is defined, otherwise make a list from legacy / current / edge. We might want to limit this further, but not at this time.
Nothing special. Applied coding style.
Several manual tests. Once merged, it has to be tested on exotic variants as we might need to add exceptions.
=> Add kernel switching functionality

.github/workflows/debian.yml
If we are going to use package as source for unit testing, its better to store base dependencies straight into package.
=> Adjust package dependencies - needed for bare cloud images

.github/workflows/debian.yml, .github/workflows/unit-tests.yml, lib/armbian-configng/config.ng.jobs.json, tests/README.md, tests/S17.conf, tests/S18.conf
Add simple unit testing mechanism. It executes tests commands and return true if expected (test CONDITION) result matches. Test executes after Debian package is being generated. Which starts at push.
Issue reference:  Requirement https://github.com/armbian/configng/pull/90 
Supports:
- testing on Pull Requests
- testing periodically
- after PR is merged and packed
- testing features on: Debian Bookworm, Debian Trixie, Ubuntu Jammy and Ubuntu Noble
Produces summary:
- test configuration files are stored in `tests/`
- name of the the file is function ID
Config options:
```
ENABLED=false|true
PREINSTALL="cmd" in order to satisfy test case
CONDITION must return 0 for test success
```
=> Enable automated functions testings of armbian-config

.github/workflows/lint.yml
Copy pasted implementation was checking executable bit, while we want to check all functions too, those which don't have that set.
Tested in private fork.
=> Bugfix: enable linter on bash .sh files, not just on executable ones

.editorconfig, .github/workflows/coding-style.yml
Checks pull requests if they comply with coding standard defined in .editorconfig.
Tested on private fork.
=> Enable coding style check action that uses .editorconfig definitions

lib/armbian-configng/config.ng.functions.sh
When installing kernels, it was not possible to install kernels from other branches and installed kernels didn't remove previous installations.
Tested legacy, edge, current, legacy, ...
=> Alternative kernels - bugfix & hardening installation

.github/workflows/lint.yml
When we are running linter, we would only like to check our changes, not scan all repository for problems.
=> Lint only changed files

lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.software.sh, tests/SW26.conf
Rework Docker install and enable automated testing routine.
Rework Docker install to use wget only. We don't need to use Curl and wget. When using BASH 4+ (which we do), we can use internal function to conduct _lowercasing_. Also improve purging by deleting the key and sources.
=> Docker improvements and enabling auto testing

.github/workflows/unit-tests.yml, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.software.sh, lib/armbian-configng/config.ng.system.sh, tests/README.md, tests/S26.conf, tests/S27.conf
Implement functionality for upgrading to latest distribution release. It only provides options, defined by build framework.
When more options are possible, it prompts:
It works the same on Ubuntu and Debian. Units tests are provided, but this still doesn't mean upgrades will be successful on users side. Feature prompts user for danger.
Issue reference:  https://github.com/armbian/build/pull/7303
Function returns false or true of second parameter "verify" is added, otherwise it does the job. It only provides option to latest possible. If we upgrade from Focal and want stable upgrade, it will upgrade to Noble. If we upgrade bullseye to unstable, it will upgrade to testing.
=> Enable distro upgrades procedure

lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json, tests/M00.conf
"disabled": true,
`select(.disabled|not) |`
"status": "disabled"
`select(.status != "disabled") `
=> 117 task Merge status and disabled into one functionality

lib/armbian-configng/config.ng.network.sh
NetPlan needs CLI needs to have . escape in order to generate valid config. Closing https://github.com/armbian/configng/issues/154
=> Escape dots in SSID name in order to be NetPlan config ready

lib/armbian-configng/config.ng.jobs.json, tools/README.md, tools/config-jobs, tools/json/config.help.json, tools/json/config.localisation.json, tools/json/config.network.json, tools/json/config.software.json, tools/json/config.system.json, tools/json/config.temp.json
This PR adds tools. this tool splits the Jobs JSON file into smaller parts. prepares for future tools, such as moving documentation generation. No new dependencies are added.
- Added Tool with options to split (`-s`) and join (`-j`) config JSON files.
- **Issue Reference:** 
- #119 
- #147 
- #93
- **Key Changes:** Functions for splitting and joining JSON files.
- **Justification:** Improves virstioning and sets up for future enhancements.
- **Dependencies:** No new dependencies introduced.
- **Document** include a simple help message -h 
- **Test 1:** Split a JSON file successfully.
- **Test 2:** Joined multiple JSON files back into one.
=> Split JSON into smaller parts + tools for its management

lib/armbian-configng/config.ng.system.sh
Another small UX improvement.
Tested with and without on Ubuntu 24.04
=> Drop DEBIAN_FRONTEND=noninteractive prefix as it shows nothing at more recent apt app

lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh, tools/json/config.system.json
There was inconsistency with this variable. It was set as OVERLAY_DIR and somewhere as OVERLAYDIR. 
Tested on device with freshly build image containing this fix https://github.com/armbian/build/pull/7351
=> Adjust OVERLAY_DIR variable to match build framework settings

README.md
=> Add tool compatibility list to the Readme.md

lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.network.sh, lib/armbian-configng/config.ng.software.sh, lib/armbian-configng/config.ng.system.sh
Somewhere we had whiptail hard coded while we should be using a wrapper function.
Search and replace.
Tested few changed and works as expected.
=> Coding style fix: replace whiptail with a wrapper function

lib/armbian-configng/config.ng.functions.sh
I think its better to go back in the menu, then exiting to the prompt.
=> Function process_input: return 1 on fail, don't exit with 1

lib/armbian-configng/config.ng.functions.sh, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.network.sh, lib/armbian-configng/config.ng.system.sh, tools/json/config.network.json
Add support for automatic restore on cancellation, retest and harden functionality.
Minimal systemdnetwork Jammy image:
- setting wired DHCP and static
- setting AP, connecting to it, rebooting, disabling it
Minimal NetworkManager Jammy image:
- setting wired DHCP and static
- setting AP, connecting to it, rebooting, disabling it
=> Harden network management and configuration

.github/workflows/unit-tests.yml, lib/armbian-configng/config.ng.jobs.json, lib/armbian-configng/config.ng.system.sh, tests/DE01.conf, tests/DE11.conf, tests/DE21.conf, tests/DE31.conf, tools/json/config.software.json
Enabling **well tested desktop variants**, disable those we need to work more on. All enabled are covered with unit tests.
Installing Armbian desktop packages + enabling respective login manager.
Odroid M1 hooked to the 1080p monitor
Armbian Jammy arm64
Armbian Bookworm arm64
=> Desktops: refactor desktop install, enable working ones, add unit tests

bin/armbian-configng
Check for sudo and prompt If NOT
Caveat:
- Breaks in serve_doc can be removed not used or moved to tools for future use.
- Will need sudo privileges to run help messages.
=> Simplify sudo check require it always.

DOCUMENTATION.md, lib/armbian-configng/config.ng.docs.sh
an additional level of nested filtering. The id fields were excluded from the main output as they are already displayed in the help section further down in the document, making them redundant in this context.
=> refactored see_full_list

.github/workflows/debian.yml
As per tittle. Resolving packaging issue.
=> Introduce new parameter that will execute a script prior to packing

CONTRIBUTING.md, README.md
Current ones had hard-coded build framework instructions. Removing that, adjust Readme.md with git clone to run instructions.
=> Add dedicated CONTRIBUTION.md and adjust README.md

tests/CINNAMON01.conf, tests/GNOME01.conf, tests/XFCE01.conf, tools/json/config.software.json
Once desktop is full, once bare. This needs to be fixed, then enabling this back.
Issue reference:  https://github.com/armbian/configng/issues/225
=> Disable desktops as we don't have consistency at build side

tools/json/config.system.json, tools/modules/system/manage_zsh.sh
Changing default shell results in error. 
- moving install and config from JSON to modules for clarity.
- fixing the problem
Closing https://github.com/armbian/configng/issues/222
=> ZSH: move functions from JSON to separate modules

tools/json/config.software.json, tools/modules/software/install_openhab.sh
- disable particular desktops, not index recreation.
- suppress service startup for OpenHab
=> Bugfix: we can't fully disable desktop due to automation

tools/json/config.system.json, tools/modules/system/release_upgrade.sh
After few testings, this is not ready yet. Disabling.
=> Disable distribution upgrade as its still pretty fragile

.github/labels.yml
We copy / pasted label system from build framework. Changing the name of label to indicate armbian-config bug instead of framework.
=> Add a label "not armbian-config" bug

tools/modules/network/default_network_config.sh, tools/modules/network/network_config.sh
- fix bug for not able to select DHCP mode on wired adaptor
- show warning that AP only works in bridge mode
- small cosmetic fixes
=> Fix slightly broken network configuration

tools/modules/system/manage_dtoverlays.sh
Possible fix for: https://github.com/armbian/configng/issues/250
@The-going
=> Add a warning when tool runs with outdated BSP package

README.md
After bonding Github organisation pages with our domain name, repository pages goes under github.armbian.com/REPOSITORY
=> Change development repository domain name to github.armbian.com

tools/json/config.system.json, tools/modules/system/manage_dtoverlays.sh
Old armbian config doesn't need changes at build time. It seems all overlays are in the same place except legacy / vendor kernels. We need to look into if exceptions are still needed:
https://github.com/armbian/config/blob/master/debian-config-functions#L58-L61
@wizbandit @stephengraf @The-going
=> Overlay management - reverting to previous logic 

tools/json/config.software.json
Using menu under Desktop gets stuck message loops. 
all sub entries seemed disabled so the parent also needs disabled.
Quick fix for disabled Desktop,
=> [bug] Need at least one enabled sub

tools/modules/system/install_headers.sh
Kernel branch information is stored in armbian-release at boot time. When we change kernel branches, we need to re-read this and add it.
=> Bugfix: read branch information when we change BSP

tools/json/config.system.json
Odroid XU4 is the only board where /boot/boot.ini way of setting boot parameters is used. Since this is not supported, makes not point showing an option in the menu.
Issue reference:  https://forum.armbian.com/topic/47782-booting-with-a-hc1-overlay
Hiding menu if files we manipulate are not present.
=> Overlay management: disable showing this option where its not supported

tools/modules/software/install_openhab.sh, tools/modules/system/apt_install_wrapper.sh, tools/modules/system/manage_desktops.sh, tools/modules/system/manage_dtoverlays.sh, tools/modules/system/manage_overlayfs.sh
no helper or modules named "overlayfs", "dtoverlay"
This oversight does not break array parsing, but does break database.
note: `dtoverlay` description is blank as was the `overlayfs` before correction. 
valid json
=> [Bugfix] feature array names, 

tools/modules/system/manage_dtoverlays.sh
There are dtbos with no BOOT_SOC, but board name in filename.
There are many of them in rockchip vendor kernel: https://github.com/armbian/linux-rockchip/tree/rk-6.1-rkr4.1/arch/arm64/boot/dts/rockchip/overlay. So set then available.
=> manage_dtoverlays: also set overlays with board name available

tools/json/config.network.json, tools/json/config.system.json, tools/modules/functions/set_runtime_variables.sh, tools/modules/network/module_nfsd.sh
Enable, manage and disable NFS daemon.
Issue reference:  https://github.com/armbian/configng/issues/242
BASH
=> System: add NFS daemon install and manipulation

.github/workflows/debian.yml
Adding dependencies for debian file generation.
Issue reference:  https://github.com/armbian/build/pull/7562 
@dimitry-ishenko added them to the main build framework, copy pasting here. We will eventually drop making .deb files twice and only install them from build framework. This should be dropped at one point https://armbian.atlassian.net/browse/AR-2562
=> Add missing deps for generating deb file

tools/modules/system/module_armbian_firmware.sh
Removes redundant install argument from pkg_install comment when installing kernels. Issue introduced by #320.
Issue reference: Fixes #333
Related documentation: N/A
Removes a redundant argument so that kernel installation works properly.
=> Closes #333 - Remove redundant install argument in module_armbian_firmware.sh

tools/modules/runtime/config.runtime.sh
Fix: error
manually testing `./bin/armbian-config --api generate_json_options` results in Invalid JSON!
```
Error: Parse error on line 683:
...e_sub_submenu_data "MenuID" "SubID" "Sub
-----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'
```
=> Remove escape character from runtime

tools/json/config.software.json, tools/modules/software/module_transmission.sh
Really minor thing but Deluge, qBittorrent and Transmission are torrent _clients_, not torrent _servers_ :)
=> Corrected torrent servers to torrent clients

tools/modules/functions/set_runtime_variables.sh, tools/modules/software/module_transmission.sh
If we want that reverse proxy can connect to the web interface, we need to allow Docker bridge subnet.
=> Transmission: add docker subnet to the whitelist

.github/workflows/unit-tests.yml, tests/NET001.conf
**Github:**
>Artifact actions v3 will be deprecated by December 5, 2024. You are receiving this email because you have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact. After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.
=> Unit tests: upgrade unit tests components to mitigate deprecation

tools/modules/software/module_docker.sh
Docker installation on some variants needs manual start.
=> Docker engine bugifix: adding service start command

tools/modules/system/manage_dtoverlays.sh
remove problem line that sources `/boot/armbianEnv.txt` no obiouse adverce effets. 
issue: https://github.com/armbian/configng/issues/349
=> [Bugfix]:  Unexpected command executed when config overlays #349

tools/modules/system/module_sshserver.sh
Point of running such server is to provide ability to rsync data in and out but rsync package is not installed by default. Lets add it.
- installing additional package to the docker instance
=> Sandboxed SSH server: add rsync to the Docker container

tools/modules/software/module_docker.sh
When we run this as a root, this variable is undefined and it errors out.
=> Module Docker: Check if SUDO_USER variable is defined

tools/modules/system/module_armbian_runners.sh
We have several scripts that are used only for internal processes. This script is not interesting for end users, so it doesn't need to have menu entry. I put it into the system folder but for the future we might have this separately. 
Install two runners with name "runner.
`armbian-config --api module_armbian_runners install gh_token=TOKEN runner_name=runner stop=02`
Purge them:
`armbian-config --api module_armbian_runners purge gh_token=TOKEN runner_name=runner stop=02`
```
Usage: module_armbian_runners <command> [switches]
Commands:  install purge
Available commands:
install		- Install or reinstall runners.
purge		- Purge runners.
Available switches:
gh_token	- token with rights to admin runners.
runner_name	- name of the runner (series).
start		- start of serie (01).
stop		- stop (01). …
```
=> Armbian internal: GitHub runners deployment script

tools/modules/functions/check_distro_status.sh, tools/modules/functions/config_interface.sh
Gauge goes from 0 - 100 / 10 seconds and proceeds.
=> Distro verification: Display warning for 10 seconds and auto continue

tools/modules/system/manage_overlayfs.sh
"enabled" is not a valid value for the option. Aside for "disabled", here are examples from /etc/overlayroot.conf:
overlayroot_cfgdisk="LABEL=OROOTCFG"
overlayroot_cfgdisk="/dev/vdb"
=> manage_overlayfs: Keep the default value of overlayroot_cfgdisk

.github/workflows/unit-tests.yml, bin/armbian-config, tests/CON002.conf, tests/CON005.conf, tests/DAT001.conf, tests/HAB001.conf, tests/HAS001.conf, tests/MAN001.conf, tests/MAN002.conf, tests/MON001.conf, tests/NET001.conf, tests/README.md
- test script can have function `testcase` which includes a script that needs to be executed
- CONDITION and PREINSTALL variables are deprecated as general condition is that function `testcase` completes
- unit tests are now run on latest Armbian images
Test config example:
```
ENABLED=true
RELEASE="bookworm:noble"
function testcase {
./bin/armbian-config --api module_cockpit install
[ -f /usr/bin/cockpit-bridge ]
}
```
Updated Readme.md in the tests folder.
=> Improve unit test system with additional test case functionality

README.md
When we are installing on a 3rd party OS, we need to supply key.
=> Add GPG key download for 3rd party distro

tools/modules/system/manage_dtoverlays.sh
Addressing non working overlay management.
Issue reference:  Closing https://github.com/armbian/configng/issues/360
```
223 bytes read in 5 ms (43 KiB/s)
Applying kernel provided DT overlay rockchip-rk3568-hk-i2c0.dtbo
254 bytes read in 4 ms (61.5 KiB/s)
Applying kernel provided DT overlay rockchip-rk3568-hk-uart1.dtbo
```
```
339 bytes read in 3 ms (110.4 KiB/s)
Applying kernel provided DT overlay sun8i-h3-analog-codec.dtbo
502 bytes read in 4 ms (122.1 KiB/s)
Applying kernel provided DT overlay sun8i-h3-uart2.dtbo
```
=> Fix wrong overlay manipulation

tools/modules/network/module_network_simple.sh
This will prevent erroring out as some devices are not up by default.
Issue reference:  https://github.com/armbian/build/pull/7750
=> Activate the specified network interface, before applying IP stack

tools/modules/system/module_zfs.sh
ZFS is not recommended to install on armhf, so lets define this in the module, even this functionality is not yet enabled.
Installation on 32b arch prompt for possible corruption, so we need to prepare this to disable function when this will be present.
=> ZFS: define architecture for ZFS module

bin/armbian-config, tests/CON005.conf, tests/DAT001.conf, tests/HAB001.conf, tests/HAS001.conf, tests/MAN001.conf, tests/MON001.conf, tests/NAV001.conf, tests/README.md, tools/modules/functions/config_interface.sh
Fixes `sanitize_input` command used with the `--api` and `--cmd` options.
Issue reference:  Closes #324.
Replaced `sanitize_input` function with simplified version called `sanitize`. Sanitation is only done on the first argument (which is a function name in case of `--api`, or a command name in case of `--cmd`).
_UPDATE:_ The final commit fixes some flawed tests, whose failure was masked by explicit `exit 0` statements in `armbian-config`.
See #324 for more details.
```
./bin/armbian-config --cmd DEV-001 # FAILED
./bin/armbian-config --cmd DEV001
./bin/armbian-config --cmd DEV002
./bin/armbian-config …
```
=> Fix sanitize

README.md, debian.conf, tools/repository/armbian-config.list, tools/repository/armbian-config.sources
Replace `armbian-config.list` with `armbian-config.sources`. This holds the same information in a newer format, deb822. APT has supported this format since version 1.1, released in 2015.
`README.md` is also updated, and some typos are fixed.
This does not affect `armbian.list`, but I could look at migrating that too if there is interest.
There are two more references to `armbian-config.list` that will also need to be updated in other repositories to merge this PR:
- armbian/build: `extensions/armbian-config.sh`
- armbian/documentation: `docs/User-Guide_Armbian-Config.md`
A migration script in a post-install hook might also be required.
Issue reference: n/a
Related documentation: [deb822](https://manpages.debian.org/bookworm/dpkg-dev/deb822.5.en.html)
=> feat: Use deb822 format for APT sources

tests/SY206.conf, tests/SY207.conf, tools/modules/software/module_adguardhome.sh, tools/modules/system/module_armbian_firmware.sh
As reported in forums, kernel switching can sometimes lead into unbootable image. This happens when package is absent at repository.
Issue reference:  https://forum.armbian.com/topic/49391-switching-from-rolling-to-stable-release-removed-the-kernel-making-system-unbootable
Problematic part is that apt returns 0 when test downloading package even we switched the repository and updated index.
Switching between rolling and stable without beta repository present.
=> Kernel switching - problems in case of network or repo issues

tools/modules/functions/set_runtime_variables.sh, tools/modules/system/module_armbian_firmware.sh
- kernel switching needs repo pinning.
- small styling fixes
=> Bugfix: Pinning is also needed otherwise kernel doesn't downgrade

tools/modules/software/module_navidrome.sh
After improving testing methodology, badly written code showed up. Fixing it.
=> Navidrom: fix problems that are popping up on unit tests

DOCUMENTATION.md, tools/modules/docs/config.docs.sh, tools/modules/system/module_armbian_firmware.sh, tools/modules/system/release_upgrade.sh
> This PR and the related PRs will require discussion or RFC before merging, particularly around handling migration of existing installations.
See main PR: https://github.com/armbian/build/pull/7790
- Replace `armbian.list` with `armbian.sources`. This holds the same information in a newer format, deb822.
- Replace HTTP with HTTPS for Armbian repositories.
=> feat: Use deb822 APT sources

.github/workflows/stale.yml
... if there is not further activity.
GHA
=> Automation: automatically close issues marked as "Can be closed?" 

tools/json/config.software.json, tools/json/config.system.json, tools/modules/functions/check_desktop.sh, tools/modules/functions/service.sh, tools/modules/functions/set_runtime_variables.sh, tools/modules/network/default_network_config.sh, tools/modules/network/default_wireless_network_config.sh, tools/modules/network/network_config.sh, tools/modules/software/module_adguardhome.sh, tools/modules/software/module_cockpit.sh, tools/modules/software/module_docker.sh, tools/modules/software/module_haos.sh, tools/modules/software/module_openhab.sh, tools/modules/software/module_pi-hole.sh, tools/modules/software/module_webmin.sh, tools/modules/system/manage_desktops.sh, tools/modules/system/module_nfs.sh, tools/modules/system/module_nfsd.sh, tools/modules/system/toggle_ssh_lastlog.sh
Add consistent interface to enable/disable, start/stop and query systemd services. This PR tries to abstract package manipulation (not entirely unlike PR #320), remove some boiler-plate and have something that's easy to maintain in the future.
For example, `srv_reload`, `srv_start`, etc. functions check if they are running inside container, and if so, will silently ignore their command.
The following functions were added:
```
srv_active  some.service
srv_daemon_reload
srv_disable some.service
srv_enable  some.service
srv_enabled some.service
srv_mask    some.service
srv_reload  some.service
srv_restart some.service
srv_start   some.service
srv_stop    some.service
srv_status  some.service
srv_unmask  some.service
```
Used `armbian-config` in interactive mode to install/uninstall several …
=> Add wrapper for service manipulation

tools/modules/system/module_armbian_kvmtest.sh
For easy testing management, we would like to drop all saved state. Internal functionality.
=> KVM management: add command to drop all saved states

tools/json/config.system.json, tools/modules/system/module_armbian_upgrades.sh
Configuration module for `unattended-upgrades` on Armbian. Module can install, remove, and configure automatic updates on the system. The script provides default Armbian configuration, which can be tweaked by end user.
- APT::Periodic::Update-Package-Lists: Updates package lists automatically.
- APT::Periodic::Download-Upgradeable-Packages: Downloads upgradeable packages automatically.
- Unattended-Upgrade::Remove-Unused-Dependencies: Removes unused dependencies after upgrades.
- Unattended-Upgrade::Automatic-Reboot: Allows automatic reboot after updates.
- Unattended-Upgrade::Automatic-Reboot-WithUsers: Reboots even with logged-in users.
=> Unattended Upgrade Manager module - reconfiguring automatic updates

tools/modules/system/module_desktop.sh
Installation of Gnome hangs in some cases.
=> Desktop install bugfix: we need to keep old configs when installing packages

tools/modules/system/module_armbian_rsyncd.sh
Fixing wrong port declaration in the module config.
=> Armbian rsyncd: fix port used in the module

.github/workflows/lint.yml, .github/workflows/unit-tests.yml
Addressing security issue: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
=> Change to different method of getting changed files

tools/modules/functions/set_runtime_variables.sh, tools/modules/system/install_headers.sh, tools/modules/system/manage_dtoverlays.sh
Show rk3588 vendor kernel overlays which don't have prefix in overlay selection section.
=> kernel: show rk3588 vendor kernel overlays in overlays section

tools/modules/system/module_armbian_firmware.sh
Switching back to vendor was not working.
=> Bugfix: allow switching from rockchip edge / current to vendor

tools/modules/functions/set_runtime_variables.sh, tools/modules/system/install_headers.sh, tools/modules/system/manage_dtoverlays.sh, tools/modules/system/module_armbian_firmware.sh
Derive "branch" and "linuxfamily" from currently installed kernel to complete the package names for hold/unhold.
"hold" and "unhold" are calling "show" with empty arguments for "branch" and "linuxfamily", so the actual values have to be calculated within the "show" function (like it is done for the "repository" function, but also including held-back packages in the grep filter).
In its current state, these variables are unset, leading to incomplete package names "linux-image--" and "linux-dtb--", so these packages can't be set to hold/unhold.
- [?] **Metadata Included:** : Does not apply afaict 
- [?] **Document Generated:** : Does not apply …
=> Derive "branch" and "linuxfamily" from currently installed kernel: fix for kernel hold / unhold

tools/modules/system/module_armbian_firmware.sh
This commit fixes an issue where the kernel selection menu would display duplicate entries for vendor kernels and wouldn't list current and edge kernels for rockchip-rk3588 boards.
Before:
after: 
Tested on Orange Pi 5 Max with Armbian 25.5.0-trunk.322.
Used the modified armbian-config to get to the kernel selection display.
=> Fix kernel selection display for rockchip-rk3588 boards

tests/gnome_desktop.conf, tests/xfce_desktop.conf, tools/json/config.software.json
This pull request includes a small change to the `tools/json/config.software.json` file. The change sets the status of the "Desktops" category to "Disabled".
Reference issue #484
* [`tools/json/config.software.json`](diffhunk://#diff-c6a5fd88d889da7957334a5e80722428f2dc9984462b4e515ae1026acc93e9ceR337): Added a "status" field with the value "Disabled" to the "Desktops" category.
>NOTE:
This disables the menu and help entries, the option is still available though the advanced --api option
```bash
/workspaces/configng (484-bug-disable-de-menu) $ sudo ./bin/armbian-config --api module_desktop help
```
Shows 
```
Usage: module_desktop <command>
Commands:  install remove disable enable status auto manual login help
Available commands:
install - Generate packages for test.
remove  -  Generate …
```
=> Disabled menu titles for Desktop Environments

tools/modules/software/module_netdata.sh
Netdata was not accessible on port 19999 because it defined no port forwarding and was also missing host network metrics due to running in a user-defined bridge network (`--network=lsio`), which isolates the container from the host’s network stack.
Switched to `--network=host` to allow Netdata to bind directly to host ports and access full network and system metrics as per [the documentation](https://learn.netdata.cloud/docs/netdata-agent/installation/docker)
=> Switch Netdata to host network for proper metrics and accessibility

tools/modules/software/module_haos.sh
As of Home Assistant Supervisor release [2024.12.0](https://github.com/home-assistant/supervisor/releases/tag/2024.12.0), support for CGroup v2 has been added. Since it's my understanding that older version of the installer (1.6.0 currently in the repository) install the latest version of HomeAssistant and its supervisor, we can safely remove this.
This update removes the explicit disabling of `systemd.unified_cgroup_hierarchy=0`, aligning with the switch to cgroupsv2 introduced in installer release [3.0.0](https://github.com/home-assistant/supervised-installer/releases/tag/3.0.0).
See this [supervised-installer ](https://github.com/home-assistant/supervised-installer/issues/372) issue for more context.
I also noticed it's set [in this file …
=> Do not disable cgroupsv2 on Home Assistant installation

tools/modules/software/module_evcc.sh, tools/modules/software/module_stirling.sh
This PR enables the **Stirling-PDF** container to automatically start after a server reboot by modifying the `docker run` command to include `--restart unless-stopped`.
**Issue reference:**  
N/A (No specific issue linked)
- **Key changes introduced by this PR:**  
- Added `--restart unless-stopped` to the `docker run` command for **Stirling-PDF**.  
- Ensures the container automatically restarts after a server reboot or unexpected shutdown.  
- Maintains service availability without manual intervention.  
- **Justification for the changes:**  
- Without the `--restart unless-stopped` flag, the **Stirling-PDF** container does not automatically start when the server reboots.  
- This change improves **reliability and uptime** by ensuring the service is always running unless explicitly …
=> Enable Auto start for Stirling-PDF after reboot

.github/workflows/pr-auto-labeler.yml
- PR creation date for quarterly tracking (job: label-by-date)
- Removes "Ready to merge" label on PR update (job: label-remove)
Github actions.
Copy from https://github.com/armbian/build
=> Improve auto-labeling - copy improvements from build fw repository

tools/modules/functions/module_default.sh
This module adds default implementation of several functions frequently used by other modules. With this module we can greatly reduce boiler-plate which is currently repeated in many other modules.
For example, to create a simple module that installs midnight commander (mc) now takes only a few lines:
```bash
module_mc()
{
local module="mc" packages="mc" services=""
module_default $1 "$module" "$packages" "$services"
}
```
You can test it as follows:
```
admin@uefi-x86:~$ armbian-config --api module_mc help
Usage: module_mc <action> [options...]
Where <action> is one of:
help        Show this help screen.
install     Install package(s) for mc.
remove      Remove package(s) for mc.
status      Check mc status (installed and/or enabled).
```
If your package actives one or more services, …
=> Default module implementation

.github/workflows/clean-workflow-logs.yml
This PR adds a scheduled GitHub Actions workflow to automatically clean up old workflow logs to help reduce storage usage and keep the repository tidy.
- **Workflow Name:** `Clean Workflow Logs`
- **Trigger:** 
- Scheduled: Every Monday at 00:00 UTC
- Manual dispatch via the Actions tab
- **Defaults:**
- Deletes logs older than 21 days
- Keeps 0 recent runs
- **Tool Used:** [`igorjs/gh-actions-clean-workflow`](https://github.com/marketplace/actions/clean-workflow)
- Reduces clutter in the Actions history
- Saves storage space in the repository
- Enables easier navigation of relevant recent workflows
Copy from other repository where it is used in production.
=> Add Scheduled Workflow to Clean Old GitHub Action Logs

DOCUMENTATION.md, tools/json/config.system.json
standardize naming in Kernel/firmware upgrades in UPD001 and UPD002
Issue reference:  #573 
Change label and documentation related to UPD002 that has kernel instead of firmware to make a single label to the end user. Only text was changed, not new dependecies to the code.
no new metadata added.
updated documentation accordingly.
recompile configng and run
=> standardize naming in Kernel/firmware upgrades

tools/json/config.network.json, tools/json/config.software.json
Relocating from armbian-config to software section. No changes.
=> Move wireguard to software section VPN

tools/config-markdown.py, tools/json/config.software.json
We need to show command / module architecture and perhaps other data, which is only stored in module. It will add more information:
- where key is present and we have a match
Add new field to JSON structure which serves to match those two - for the purpose of making proper documentation.
=> Match JSON and modules in order to read data stored in modules

tools/include/markdown/FIL001-footer.md
=> Fileserver: fixing typo that broke rendering of documentation

tools/modules/network/network_config.sh
Currently, if there is more than a single wireless interface, say wlan0 and wlan1, and I've setup a hotspot on wlan0 and want to connect as a client using wlan1, selecting wlan1 on the script will still show a dialogue with the option to disable the hotspot instead of allowing me to do as I please with it(`ap` or `sta`).
Now this solution introduces another problem which is that the script currently does not support setting up more than a single access point(doing so will overwrite the previously defined `/etc/hostapd/hostapd.conf`), we could instead disable the "become an access point" option in the `else` branch for now and this could be tackled individually in another PR in the future if desired.
Issue reference:  -
Related documentation: -
The proposed fix is simply to grep …
=> Network config: Show the "disable hotspot" dialog only if there is an active hotspot on the selected interface.

tools/modules/software/module_wireguard.sh
Fixing logic  to supress errors.
=> Wireguard: suppress errors if Docker is not yet installed

tools/include/markdown/PIH001-footer.md, tools/include/markdown/PIH001-header.md, tools/include/markdown/UNB001-footer.md, tools/json/config.software.json, tools/modules/runtime/config.runtime.sh, tools/modules/software/module_pi-hole.sh, tools/modules/software/module_unbound.sh
- change Unbound external port to 8053
- fix password set on Pi-hole
- ask for password after installation
- install and use Unbound with Pi-hole by default
- improve Pi-hole documentation
- purge of Unbound and Pi-hole were not removing folders
- set link to webadmin from armbian-config
- move default web port of Pi-hole from 80 to 8811
=> Pi-hole: link with Unbound by default, change default port, bugfixes

tools/modules/system/manage_dtoverlays.sh
Pull request #614 updated per coderabbit comments / suggestions.
Addresses issues #612 and #592 where overlays are not applied because the overlay_prefix gets included in the overlay name that is written to the _overlays=_ line in armbianEnv.txt .
* Subtract _overlay_prefix_ from names in _newoverlays_ before checking _newoverlays_ against _overlay_ name from arbmianEnv.txt
* Subtract _overlay_prefix_ from _overlay_ before writing to armbianEnv.txt
Overlays do not load if _prefix_ is set in armbianEnv.txt because the prefix is repeated on the overlay name.
no updates or additions required
none generated
- Test run on Libre Renegade. armbianEnv.txt has _prefix_ set to _rockchip_
- Ran armbian-config and selected "rockchip-rk3328-i2c0" from available overlays. Saved and rebooted.
- Verifed …
=> Update to manage_dtoverlays.sh for overlay_prefix handling (revised)

.github/workflows/validate-json.yml
This pull request adds a new GitHub Actions job to automatically check for duplicate port values defined in `module_options` across all .sh files in `tools/modules/` and its sub-directories.
🔍 What it does:
- Scans all .sh files under tools/modules/**
- Looks for entries in the form ["module_name,port"]="1234"
- Identifies and reports any duplicate port values
- Fails the check if duplicates are found, with details in the GitHub Actions summary
🎯 Purpose:
Helps prevent port conflicts in module definitions by enforcing unique port assignments at CI level.
=> CI: add GitHub Action to detect duplicate module ports

tools/modules/software/module_jellyfin.sh
It started - innocently - as an effort to run Jellyfin with armbian-config on a ROCK 5C Lite.
I thought, "Oh, I know... I'll use Portainer to check what went wrong. Look, it's just there... waiting to be installed, and that's it!"
A reasonable pursuit.... and deceptively convenient-looking one as well!
But Portainer, you see, has rules. Rules like “[thou shalt NOT have a password shorter than the palm of your hand](https://github.com/portainer/portainer/issues/6904)”, even when you just want to test something on a single-board computer in the corner of your desk, surrounded by grunts, coffee and passive-cooled heat sinks.
So I invented a password. It was… expressive. It spoke of the way I felt about the portainer developers, and the world where holding your users hostage, and making them …
=> I observed the wave function collapsing into a string to break the event horizon, and wished it away before it could

tools/json/config.software.json
Both Trixie and Bookworm are working while other variants (sid / bullseye) are anyway not supported, while they still might work.
=> Home Assistant: Expand requirement to whole Debian

tools/modules/software/module_haos.sh
On the host machine we need to use systemd service commands, not wrapped from armbian-config as they are not present.
=> Use systemd function and not wrapped on

tools/include/markdown/LTSREL-header.md, tools/include/markdown/ROLREL-header.md, tools/json/config.system.json, tools/modules/functions/package.sh, tools/modules/system/release_upgrade.sh
Enable release upgrades from armbian-config
Issue reference:  https://github.com/armbian/build/pull/8569
=> Fix, improve and enable distribution upgrade routines
